import libs = libsimplewebp%lib{simplewebp}

./: exe{driver}: c{driver} $libs
exe{driver}: fsdir{data}: include = adhoc
exe{driver}: test.options = $posix_string([dir_path] $out_base/data)

fsdir{data}:
% update
{{
  diag ln $>
  rm -f $out_base/data
  ln -s $posix_string([dir_path] $src_base/data) $out_base/data
}}
% clean
{{
  rm -f $out_base/data
}}
